delete http://localhost:3003/api/blogs/5ed01fc368f03b0d105df3d2 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1ZGUiLCJpZCI6IjVlZDY1MTI0YTE0ZTI2NGZmYzVkNmQyYiIsImlhdCI6MTU5MTEwMzgwMX0.0of6EyDw0VoLIoL110CZ8DF3RxBH2Vbp_VKxD3FqvAs

{
    "hyvis": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVlY2ZlMzczNjhlMmI4MDNjNGRmZDJlMiIsImlhdCI6MTU5MTEwMzk3Mn0.bf-Ij0rS9HOkv9BPhwekG12Q0_UlJwXwUt0kXluFC6Q",
    "pahis": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1ZGUiLCJpZCI6IjVlZDY1MTI0YTE0ZTI2NGZmYzVkNmQyYiIsImlhdCI6MTU5MTEwMzgwMX0.0of6EyDw0VoLIoL110CZ8DF3RxBH2Vbp_VKxD3FqvAs"
}